% analyzes data generated by run_multiq

load('esn_fps.mat','FPs');
load('data/net3.mat','net','p');
load('data/q3.mat','W','mu','we');

Wo_interval = p.Wo_interval;
nWos = size(FPs,1);
nIC = size(FPs,2);

% fraction of eigenvalues that are unstable
num_unstable = zeros(nIC,nWos);

for i=1:nWos
   X = zeros(nIC,N);
   for j=1:nIC
      fprintf('%d, %d\n',i,j);
      x_star = reshape(FPs(i,j,:),N,1);
      J = esn_jacobian(x_star,net);
      E = eig(J); % eigenvalues
      R = real(E); % real components of eigenvalues
      %X(j,:) = x_star;
      % weighted sum by principal component
      
      num_unstable(j,i) = sum(R>0);
   end
   
%    X = bsxfun(@minus,X,mu);
%    X = bsxfun(@rdivide,X,we);
%    Y = X*W; % rows = observations, columns = coordinates
%    trajectories_pca{i}=Y(:,1:3);

end



plot((1:nWos)*Wo_interval, num_unstable,'ro');
ylabel('number of unstable eigenvalues');
xlabel('training iteration');